## saved as .gitpod.yml in root repo-dir
## Start (After exporting GITPOD_TOKEN) :: bash <(curl -qfsSL "https://raw.githubusercontent.com/Azathothas/Inventory_Ingestor/main/.gitpod.sh")
## This will create two terminals : [1: Start --> Live Preview || 2:Stop --> Auto Stops after Start has Finished]
## Assumes correct env:vars have been set at : https://gitpod.io/user/variables
## Live View of Workspaces :: https://gitpod.io/workspaces 
## DOCS :: https://www.gitpod.io/docs/references/gitpod-yml
##      :: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  #Configure
    - name: configure
      init: sleep 2
      command: |
          gp timeout set 30m 2>/dev/null
          gp timeout show

  #Main Tasks
    - name: Start
      before: |
          cd /workspace/Inventory_Ingestor
      init: |
          sudo apt-get update -y && sudo apt-get install tmux -y
      command: |
          #ENV VARS are injected & setup automatically
          #tmux new-session -s "puredns" -d "bash <(curl -qfsSL https://raw.githubusercontent.com/Azathothas/Inventory_Ingestor/main/.github/scripts/puredns_setup_gitpod.sh) ; exec $SHELL"
          bash <(curl -qfsSL "https://raw.githubusercontent.com/Azathothas/Inventory_Ingestor/main/.github/scripts/puredns_setup_gitpod.sh") && gp sync-done "completed"

  #Btop Stats
    - name: btop
      init: sleep 300
      command: |
          btop

  #PTS/TTY Stats
    - name: pts-tty
      init: sleep 2
      command: |
          while true; do sudo ps -ef | grep 'tty\|pts'; gp top ; sleep 1; done

  #Cleanup
    - name: Stop
      init: gp sync-await completed
      command: |
          gp tasks list
          gp top
          gp stop
